//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class cleaning_schedule
    {
        public int cleaning_schedule_id { get; set; }
        public System.DateTime cleaning_start_time { get; set; }
        public System.DateTime cleaning_end_time { get; set; }
        public int room_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual room room { get; set; }
        public virtual employee employee { get; set; }
    }
}
