//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class cleaning_schedule
    {
        public int cleaning_schedule_id { get; set; }
        public System.DateTime cleaning_start_time { get; set; }
        public System.DateTime cleaning_end_time { get; set; }
        public int room_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual room room { get; set; }
        public virtual employee employee { get; set; }
    }
}
