//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        public int credential_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
