//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        public int credential_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
