//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.cleaning_schedule = new HashSet<cleaning_schedule>();
            this.credential = new HashSet<credential>();
            this.reservation = new HashSet<reservation>();
            this.working_schedule = new HashSet<working_schedule>();
            this.service_request = new HashSet<service_request>();
        }
    
        public int employee_id { get; set; }
        public string employye_first_name { get; set; }
        public string employye_middle_name { get; set; }
        public string employee_last_name { get; set; }
        public string employee_phone_number { get; set; }
        public string employee_passport_serial_number { get; set; }
        public string tax_payer_id { get; set; }
        public decimal wage { get; set; }
        public int position_id { get; set; }
        public string employee_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cleaning_schedule> cleaning_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credential> credential { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<working_schedule> working_schedule { get; set; }
        public virtual employee_position employee_position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_request> service_request { get; set; }
    }
}
