//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrance_log
    {
        public int entrance_log_id { get; set; }
        public System.DateTime log_time { get; set; }
        public int parking_spot_id { get; set; }
        public string status { get; set; }
    
        public virtual parking_spot parking_spot { get; set; }
    }
}
