//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrance_log
    {
        public int entrance_log_id { get; set; }
        public System.DateTime log_time { get; set; }
        public int parking_spot_id { get; set; }
        public string status { get; set; }
    
        public virtual parking_spot parking_spot { get; set; }
    }
}
