//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public decimal payment_sum { get; set; }
        public System.DateTime payment_date { get; set; }
        public int reservation_id { get; set; }
        public int payment_type_id { get; set; }
    
        public virtual reservation reservation { get; set; }
        public virtual payment_type payment_type { get; set; }
    }
}
