//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_request
    {
        public int service_request_id { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> service_provided_time { get; set; }
        public int additional_service_id { get; set; }
        public int reservation_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual additional_service additional_service { get; set; }
        public virtual employee employee { get; set; }
        public virtual reservation reservation { get; set; }
    }
}
