//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_request
    {
        public int service_request_id { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> service_provided_time { get; set; }
        public int additional_service_id { get; set; }
        public int reservation_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual additional_service additional_service { get; set; }
        public virtual employee employee { get; set; }
        public virtual reservation reservation { get; set; }
    }
}
