//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_schedule
    {
        public int working_schedule_id { get; set; }
        public System.DateTime shift_start_time { get; set; }
        public System.DateTime shift_end_time { get; set; }
        public int employee_id { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
